version: '3'

services :
    backend :
        restart : unless-stopped
        build : ./backend
        container_name: jobxp-backend-container
        networks: 
            - jobxp-network
        ports : 
            - 3000:3000
        depends_on: 
            - db
    
    frontend :
        build : ./frontend
        volumes :
            - ./frontend/html_files/:/usr/share/nginx/html
        container_name: jobxp-frontend-container
        ports :
            - 8000:80
        networks: 
            - jobxp-network
        depends_on: 
            - backend
            - db

    db :
        container_name: jobxp-database-container
        image : mysql:latest
        volumes :
            - ./database/data:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d/:ro
            - .:/app    
        ports :
            - 3305:3306
        restart : always
        environment :
            MYSQL_ROOT_PASSWORD : root
            MYSQL_DATABASE : database
            MYSQL_USER: user 
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_HOST : '%'
        networks : 
            - jobxp-network
            
        security_opt:
            - seccomp:unconfined

networks : 
    jobxp-network :
        driver: bridge
