version: '3'

services :
    backend :
        build : ./backend
        container_name: jobxp-backend-container
    
    frontend :
        build : ./frontend
        volumes :
            - ./frontend/html_files/:/usr/share/nginx/html
        container_name: jobxp-frontend-container
        ports :
            - "8000:80"
